# Generated by Django 5.2.8 on 2026-09-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAVA_ACADEMI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دوره')),
                ('description', models.TextField(verbose_name='توضیحات دوره')),
                ('teacher', models.CharField(max_length=150, verbose_name='مدرس')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('price', models.PositiveIntegerField(verbose_name='شهریه')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
    ]
