# Generated by Django 5.2.8 on 2026-10-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAVA_ACADEMI', '0006_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='message_en',
            field=models.TextField(default='', verbose_name='متن انگلیسی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='message_fa',
            field=models.TextField(default='', verbose_name='متن فارسی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='عنوان انگلیسی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='title_fa',
            field=models.CharField(default='', max_length=200, verbose_name='عنوان فارسی'),
            preserve_default=False,
        ),
    ]
